apiVersion: v1
baseDomain: openshift.sw.gemilang
metadata:
  name: ocp4
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
networking:
  clusterNetworks:
  - cidr: 10.254.0.0/16
    hostPrefix: 24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    vcenter: 192.168.100.10
    username: adminstrator@vcenter.openshift.sw.gemilang
    password: add-your-password-vcenter-here
    datacenter: swgdatacenter
    defaultDatastore: datastore1
fips: false
pullSecret: 'add-your-pull-secret-here'
sshKey: 'add-your-public-ssh-key-here'
