---

- name: ensure hostname is set correctly
  hostname: 
    name: "{{ inventory_hostname }}"
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')
  register: hostnameresult

- name: unconditionally reboot the machines
  reboot:
  when: hostnameresult.changed